name: RSS Watchdog

on:
  schedule:
    - cron: '*/15 * * * *' # Runs every 15 minutes
  workflow_dispatch: # Allows you to click a button to run it manually

permissions:
  contents: write # Allows the bot to save the "sent_posts.txt" file

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run RSS Script
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_LIST: ${{ secrets.RECIPIENT_LIST }}
        run: python rss_bot.py
      
      - name: Save History (Commit changes)
        run: |
          git config --global user.name 'RSS Bot'
          git config --global user.email 'bot@noreply.github.com'
          git add sent_posts.txt
          git commit -m "Updated sent posts history" || exit 0
          git push
